name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-14
    name: macOS-arm64

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: mlugg/setup-zig@v2
        with:
          version: "0.15.2"

      - name: Install dependencies
        run: brew install sdl3 luajit shaderc spirv-cross

      - name: Build
        run: zig build

      - name: Test
        run: zig build test
